// src/queue-tickets/dto/create-queue-ticket.dto.ts
import { IsString, IsInt, IsNotEmpty, IsOptional } from 'class-validator';

export class CreateQueueTicketDto {
  // Removed: ticketNumber will be generated by the service
  // @IsString()
  // @IsNotEmpty()
  // ticketNumber: string;

  @IsString()
  @IsNotEmpty()
  customerName: string;

  // Removed: customerPhone as requested
  // @IsOptional()
  // @IsPhoneNumber('PH', { message: 'Customer phone must be a valid Philippine phone number.' })
  // customerPhone?: string | null;

  // Removed: customerEmail as requested
  // @IsOptional()
  // @IsEmail({}, { message: 'Customer email must be a valid email address.' })
  // customerEmail?: string | null;

  // Renamed from customerCategoryId to categoryId and kept as NotEmpty based on previous errors
  @IsInt()
  @IsNotEmpty()
  categoryId: number;

  @IsInt()
  @IsNotEmpty()
  branchId: number;

  @IsInt()
  @IsNotEmpty()
  currentStatusId: number;

  @IsOptional()
  @IsInt()
  assignedToWindowId?: number | null;

  @IsOptional()
  @IsInt()
  assignedToStaffId?: number | null;

  @IsOptional()
  @IsString()
  serviceType?: string | null;

  // These fields are typically managed by the backend or updated later,
  // so they are kept optional if you ever need to send them.
  @IsOptional()
  queuedAt?: Date;

  @IsOptional()
  issuedByUserId?: number | null;

  @IsOptional()
  calledAt?: Date;

  @IsOptional()
  servedAt?: Date;

  @IsOptional()
  cancelledById?: number | null;

  @IsOptional()
  @IsString()
  visibilityStatus?: string;
}
